[package]
name = "atcoder1"
version = "0.1.0"
authors = ["makky <cutting-edgedevise@outlook.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
